-- 이노레이블 organization 테이블 생성
-- org_unit enum이 없으면 먼저 생성

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'org_unit') THEN
    CREATE TYPE public.org_unit AS ENUM ('excel', 'crew');
  END IF;
END
$$;

CREATE TABLE IF NOT EXISTS public.organization (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  unit public.org_unit NOT NULL,
  profile_id uuid REFERENCES public.profiles(id),
  name text NOT NULL,
  role text NOT NULL,
  position_order int DEFAULT 0 NOT NULL,
  parent_id bigint REFERENCES public.organization(id),
  image_url text,
  social_links jsonb,
  profile_info jsonb,
  is_live boolean DEFAULT false NOT NULL,
  is_active boolean DEFAULT true NOT NULL,
  current_rank text,
  current_rank_id bigint,
  total_contribution numeric DEFAULT 0 NOT NULL,
  season_contribution numeric DEFAULT 0 NOT NULL,
  total_prize numeric DEFAULT 0 NOT NULL,
  total_penalty numeric DEFAULT 0 NOT NULL,
  prize_balance numeric DEFAULT 0 NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL
);

-- RLS 활성화
ALTER TABLE public.organization ENABLE ROW LEVEL SECURITY;

-- 공개 읽기 정책
CREATE POLICY "organization_public_read" ON public.organization
  FOR SELECT USING (true);

-- 관리자 전체 권한
CREATE POLICY "organization_admin_all" ON public.organization
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid()
      AND profiles.role IN ('admin', 'superadmin')
    )
  );
