-- =============================================================
-- INNO LABEL: 전체 데이터베이스 스키마 (2026-02-18)
-- Supabase SQL Editor에서 한 번에 실행
-- database.ts 기준 완전 통합 버전
-- =============================================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =============================================================
-- PART 1: ENUM 타입
-- =============================================================

DO $$ BEGIN
  CREATE TYPE public.user_role AS ENUM ('member', 'bj', 'vip', 'moderator', 'admin', 'superadmin');
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  CREATE TYPE public.org_unit AS ENUM ('excel', 'crew');
EXCEPTION WHEN duplicate_object THEN null;
END $$;

-- =============================================================
-- PART 2: 핵심 테이블
-- =============================================================

-- 1. Profiles (회원 프로필)
CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL PRIMARY KEY,
  nickname text NOT NULL,
  email text,
  full_name text,
  avatar_url text,
  role public.user_role DEFAULT 'member' NOT NULL,
  unit public.org_unit,
  total_donation bigint DEFAULT 0,
  soop_id text,
  pandatv_id text,
  account_type text DEFAULT 'real' CHECK (account_type IN ('real', 'virtual', 'system')),
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);

-- 2. Seasons (시즌)
CREATE TABLE IF NOT EXISTS public.seasons (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  start_date date NOT NULL,
  end_date date,
  is_active boolean DEFAULT false NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL
);

-- 3. BJ 직급 마스터 (여왕~쌉노예 12단계)
CREATE TABLE IF NOT EXISTS public.bj_ranks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  level int NOT NULL,
  display_order int NOT NULL,
  color text,
  emoji text,
  tier text CHECK (tier IN ('royal', 'noble', 'servant', 'slave')),
  icon_url text,
  description text,
  created_at timestamptz DEFAULT now() NOT NULL
);

-- 4. Organization (조직도)
CREATE TABLE IF NOT EXISTS public.organization (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  unit public.org_unit NOT NULL,
  profile_id uuid REFERENCES public.profiles(id),
  name text NOT NULL,
  role text NOT NULL,
  position_order int DEFAULT 0 NOT NULL,
  parent_id bigint REFERENCES public.organization(id),
  image_url text,
  social_links jsonb,
  profile_info jsonb,
  is_live boolean DEFAULT false NOT NULL,
  is_active boolean DEFAULT true NOT NULL,
  current_rank text,
  current_rank_id bigint REFERENCES public.bj_ranks(id),
  total_contribution numeric DEFAULT 0 NOT NULL,
  season_contribution numeric DEFAULT 0 NOT NULL,
  total_prize numeric DEFAULT 0 NOT NULL,
  total_penalty numeric DEFAULT 0 NOT NULL,
  prize_balance numeric DEFAULT 0 NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL
);

-- 5. Episodes (에피소드)
CREATE TABLE IF NOT EXISTS public.episodes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_id bigint REFERENCES public.seasons(id) NOT NULL,
  episode_number int NOT NULL,
  title text NOT NULL,
  broadcast_date date NOT NULL,
  is_rank_battle boolean DEFAULT false NOT NULL,
  description text,
  is_finalized boolean DEFAULT false NOT NULL,
  finalized_at timestamptz,
  representative_bj_total jsonb,
  created_at timestamptz DEFAULT now() NOT NULL
);

-- 6. Donations (후원 내역)
CREATE TABLE IF NOT EXISTS public.donations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  donor_id uuid REFERENCES public.profiles(id),
  donor_name text NOT NULL,
  amount bigint NOT NULL,
  season_id bigint REFERENCES public.seasons(id) NOT NULL,
  episode_id bigint REFERENCES public.episodes(id),
  unit public.org_unit,
  message text,
  target_bj text,
  donated_at timestamptz,
  created_at timestamptz DEFAULT now() NOT NULL
);

-- 7. VIP Rewards (VIP 보상)
CREATE TABLE IF NOT EXISTS public.vip_rewards (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id uuid REFERENCES public.profiles(id) NOT NULL,
  season_id bigint REFERENCES public.seasons(id) NOT NULL,
  episode_id bigint REFERENCES public.episodes(id),
  rank int NOT NULL,
  personal_message text,
  dedication_video_url text,
  created_at timestamptz DEFAULT now() NOT NULL
);

-- 8. VIP Images
CREATE TABLE IF NOT EXISTS public.vip_images (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reward_id bigint REFERENCES public.vip_rewards(id) ON DELETE CASCADE NOT NULL,
  image_url text NOT NULL,
  title text,
  order_index int DEFAULT 0 NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL
);

-- 9. Signatures (시그니처)
CREATE TABLE IF NOT EXISTS public.signatures (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sig_number int NOT NULL,
  title text NOT NULL,
  description text,
  thumbnail_url text,
  unit public.org_unit NOT NULL,
  is_group boolean DEFAULT false,
  created_at timestamptz DEFAULT now() NOT NULL,
  CONSTRAINT signatures_unit_sig_number_unique UNIQUE (unit, sig_number)
);

-- 10. Signature Videos
CREATE TABLE IF NOT EXISTS public.signature_videos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  signature_id bigint NOT NULL REFERENCES public.signatures(id) ON DELETE CASCADE,
  member_id bigint NOT NULL REFERENCES public.organization(id) ON DELETE CASCADE,
  video_url text NOT NULL,
  cloudflare_uid varchar(64),
  created_at timestamptz DEFAULT now() NOT NULL,
  CONSTRAINT signature_videos_sig_member_unique UNIQUE (signature_id, member_id)
);

-- 11. Schedules (일정)
CREATE TABLE IF NOT EXISTS public.schedules (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  description text,
  unit public.org_unit,
  event_type text CHECK (event_type IN ('broadcast', 'collab', 'event', 'notice', '休')) NOT NULL,
  start_datetime timestamptz NOT NULL,
  end_datetime timestamptz,
  location text,
  is_all_day boolean DEFAULT false NOT NULL,
  color text,
  created_by uuid REFERENCES public.profiles(id),
  created_at timestamptz DEFAULT now() NOT NULL
);

-- 12. Timeline Events
CREATE TABLE IF NOT EXISTS public.timeline_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_date date NOT NULL,
  title text NOT NULL,
  description text,
  image_url text,
  category text,
  season_id bigint REFERENCES public.seasons(id),
  order_index int DEFAULT 0,
  created_at timestamptz DEFAULT now() NOT NULL
);

-- 13. Notices (공지사항)
CREATE TABLE IF NOT EXISTS public.notices (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  content text NOT NULL,
  category text CHECK (category IN ('official', 'excel', 'crew')) NOT NULL,
  thumbnail_url text,
  is_pinned boolean DEFAULT false NOT NULL,
  view_count bigint DEFAULT 0 NOT NULL,
  author_id uuid REFERENCES public.profiles(id),
  display_order int,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);

-- 14. Notice Attachments (공지 첨부파일)
CREATE TABLE IF NOT EXISTS public.notice_attachments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  notice_id bigint REFERENCES public.notices(id) ON DELETE CASCADE NOT NULL,
  file_url text NOT NULL,
  file_name text NOT NULL,
  file_type text CHECK (file_type IN ('image', 'video')) NOT NULL,
  file_size bigint,
  display_order int DEFAULT 0,
  created_at timestamptz DEFAULT now() NOT NULL
);

-- 15. Posts (게시글)
CREATE TABLE IF NOT EXISTS public.posts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  board_type text CHECK (board_type IN ('free', 'vip', 'anonymous', 'recommend', 'meme', 'report')) NOT NULL,
  title text NOT NULL,
  content text NOT NULL,
  author_id uuid REFERENCES public.profiles(id) NOT NULL,
  view_count bigint DEFAULT 0 NOT NULL,
  like_count bigint DEFAULT 0 NOT NULL,
  comment_count bigint DEFAULT 0 NOT NULL,
  is_anonymous boolean DEFAULT false NOT NULL,
  is_deleted boolean DEFAULT false NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);

-- 16. Comments (댓글)
CREATE TABLE IF NOT EXISTS public.comments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id bigint REFERENCES public.posts(id) ON DELETE CASCADE NOT NULL,
  author_id uuid REFERENCES public.profiles(id) NOT NULL,
  content text NOT NULL,
  parent_id bigint REFERENCES public.comments(id),
  is_anonymous boolean DEFAULT false NOT NULL,
  is_deleted boolean DEFAULT false NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL
);

-- 17. Post Likes
CREATE TABLE IF NOT EXISTS public.post_likes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id bigint REFERENCES public.posts(id) ON DELETE CASCADE NOT NULL,
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  UNIQUE (post_id, user_id)
);

-- 18. Media Content (Shorts/VOD)
CREATE TABLE IF NOT EXISTS public.media_content (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content_type text CHECK (content_type IN ('shorts', 'vod')) NOT NULL,
  title text NOT NULL,
  description text,
  thumbnail_url text,
  video_url text NOT NULL,
  cloudflare_uid text,
  unit public.org_unit,
  duration int,
  view_count bigint DEFAULT 0 NOT NULL,
  is_featured boolean DEFAULT false NOT NULL,
  parent_id bigint,
  part_number int DEFAULT 1,
  total_parts int DEFAULT 1,
  created_at timestamptz DEFAULT now() NOT NULL
);

-- 19. Live Status (라이브 상태)
CREATE TABLE IF NOT EXISTS public.live_status (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id bigint REFERENCES public.organization(id) NOT NULL,
  platform text CHECK (platform IN ('chzzk', 'twitch', 'youtube', 'pandatv', 'sooptv')) NOT NULL,
  stream_url text NOT NULL,
  thumbnail_url text,
  is_live boolean DEFAULT false NOT NULL,
  viewer_count int DEFAULT 0 NOT NULL,
  last_checked timestamptz DEFAULT now() NOT NULL,
  CONSTRAINT live_status_member_platform_unique UNIQUE (member_id, platform)
);

-- 20. Banners (배너)
CREATE TABLE IF NOT EXISTS public.banners (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text,
  image_url text NOT NULL,
  link_url text,
  display_order int DEFAULT 0 NOT NULL,
  is_active boolean DEFAULT true NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);

-- 21. Tribute Guestbook (방명록)
CREATE TABLE IF NOT EXISTS public.tribute_guestbook (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tribute_user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  author_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  author_name text NOT NULL,
  message text NOT NULL CHECK (char_length(message) <= 500),
  is_member boolean DEFAULT false,
  is_approved boolean DEFAULT true,
  is_deleted boolean DEFAULT false,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);

-- 22. BJ Thank You Messages (BJ 감사 메시지)
CREATE TABLE IF NOT EXISTS public.bj_thank_you_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vip_profile_id uuid REFERENCES public.profiles(id) NOT NULL,
  bj_member_id bigint REFERENCES public.organization(id) NOT NULL,
  message_type text CHECK (message_type IN ('text', 'image', 'video')) NOT NULL,
  content_text text,
  content_url text,
  is_public boolean DEFAULT true,
  is_deleted boolean DEFAULT false,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);

-- 23. VIP Personal Messages
CREATE TABLE IF NOT EXISTS public.vip_personal_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vip_profile_id uuid REFERENCES public.profiles(id) NOT NULL,
  author_id uuid REFERENCES public.profiles(id) NOT NULL,
  message_type text DEFAULT 'text' CHECK (message_type IN ('text', 'image', 'video')),
  content_text text,
  content_url text,
  is_public boolean DEFAULT true,
  is_deleted boolean DEFAULT false,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);

-- 24. VIP Message Comments
CREATE TABLE IF NOT EXISTS public.vip_message_comments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_id bigint REFERENCES public.vip_personal_messages(id) ON DELETE CASCADE NOT NULL,
  author_id uuid REFERENCES public.profiles(id) NOT NULL,
  content text NOT NULL,
  parent_id bigint REFERENCES public.vip_message_comments(id),
  is_deleted boolean DEFAULT false,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);

-- 25. Rank Battle Records (명예의 전당)
CREATE TABLE IF NOT EXISTS public.rank_battle_records (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_id bigint REFERENCES public.seasons(id) NOT NULL,
  battle_number int NOT NULL,
  rank int NOT NULL,
  donor_id uuid REFERENCES public.profiles(id),
  donor_name text NOT NULL,
  total_amount bigint NOT NULL,
  finalized_at timestamptz DEFAULT now(),
  created_at timestamptz DEFAULT now() NOT NULL,
  UNIQUE (season_id, battle_number, rank)
);

-- 26. Total Donation Rankings (총 후원 랭킹)
CREATE TABLE IF NOT EXISTS public.total_donation_rankings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rank int NOT NULL UNIQUE,
  donor_id uuid REFERENCES public.profiles(id),
  donor_name text NOT NULL,
  total_amount bigint NOT NULL,
  donation_count int DEFAULT 0,
  top_bj text,
  is_permanent_vip boolean DEFAULT false,
  updated_at timestamptz DEFAULT now(),
  created_at timestamptz DEFAULT now() NOT NULL
);

-- 27. Season Donation Rankings (시즌별 후원 랭킹)
CREATE TABLE IF NOT EXISTS public.season_donation_rankings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  season_id bigint REFERENCES public.seasons(id) NOT NULL,
  rank int NOT NULL,
  donor_id uuid REFERENCES public.profiles(id),
  donor_name text NOT NULL,
  total_amount bigint NOT NULL,
  donation_count int DEFAULT 0,
  top_bj text,
  unit public.org_unit,
  updated_at timestamptz DEFAULT now(),
  created_at timestamptz DEFAULT now() NOT NULL,
  UNIQUE (season_id, rank)
);

-- 28. BJ Episode Performances (BJ별 에피소드 성적)
CREATE TABLE IF NOT EXISTS public.bj_episode_performances (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  episode_id bigint REFERENCES public.episodes(id) NOT NULL,
  bj_member_id bigint REFERENCES public.organization(id) NOT NULL,
  donation_hearts int DEFAULT 0,
  donation_count int DEFAULT 0,
  heart_score int DEFAULT 0,
  contribution int DEFAULT 0,
  final_rank int,
  rank_result text,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL,
  UNIQUE (episode_id, bj_member_id)
);

-- 29. Legacy Donation Totals
CREATE TABLE IF NOT EXISTS public.legacy_donation_totals (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  donor_name text NOT NULL,
  total_amount bigint NOT NULL,
  note text,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);

-- 30. BJ Rank History (직급 변동 이력)
CREATE TABLE IF NOT EXISTS public.bj_rank_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bj_member_id bigint REFERENCES public.organization(id) NOT NULL,
  episode_id bigint REFERENCES public.episodes(id),
  season_id bigint REFERENCES public.seasons(id),
  rank_id bigint REFERENCES public.bj_ranks(id) NOT NULL,
  previous_rank_id bigint REFERENCES public.bj_ranks(id),
  change_reason text,
  is_rank_battle boolean DEFAULT false,
  battle_number int,
  created_at timestamptz DEFAULT now() NOT NULL
);

-- 31. Contribution Logs (기여도 변동 로그)
CREATE TABLE IF NOT EXISTS public.contribution_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bj_member_id bigint REFERENCES public.organization(id) NOT NULL,
  episode_id bigint REFERENCES public.episodes(id),
  season_id bigint REFERENCES public.seasons(id),
  amount int NOT NULL,
  reason text NOT NULL,
  balance_after int NOT NULL,
  event_type text,
  created_by uuid REFERENCES public.profiles(id),
  created_at timestamptz DEFAULT now() NOT NULL
);

-- 32. Prize Penalties (상벌금 기록)
CREATE TABLE IF NOT EXISTS public.prize_penalties (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bj_member_id bigint REFERENCES public.organization(id) NOT NULL,
  episode_id bigint REFERENCES public.episodes(id),
  season_id bigint REFERENCES public.seasons(id),
  type text CHECK (type IN ('prize', 'penalty')) NOT NULL,
  amount int NOT NULL CHECK (amount > 0),
  description text,
  is_paid boolean DEFAULT false,
  paid_at timestamptz,
  payment_note text,
  created_by uuid REFERENCES public.profiles(id),
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);

-- 33. Episode Teams (에피소드별 팀 구성)
CREATE TABLE IF NOT EXISTS public.episode_teams (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  episode_id bigint REFERENCES public.episodes(id) NOT NULL,
  team_name text NOT NULL,
  team_type text CHECK (team_type IN ('major_minor', 'queen_princess', 'mercenary', 'custom')) NOT NULL,
  team_color text,
  description text,
  created_at timestamptz DEFAULT now() NOT NULL
);

-- 34. Episode Team Members
CREATE TABLE IF NOT EXISTS public.episode_team_members (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id bigint REFERENCES public.episode_teams(id) ON DELETE CASCADE NOT NULL,
  bj_member_id bigint REFERENCES public.organization(id) NOT NULL,
  role text DEFAULT 'member' CHECK (role IN ('leader', 'member', 'mercenary')),
  partner_bj_id bigint REFERENCES public.organization(id),
  partner_name text,
  stats jsonb,
  created_at timestamptz DEFAULT now() NOT NULL,
  UNIQUE (team_id, bj_member_id)
);

-- 35. Episode Matchups (1vs1 매칭)
CREATE TABLE IF NOT EXISTS public.episode_matchups (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  episode_id bigint REFERENCES public.episodes(id) NOT NULL,
  bj_member_1_id bigint REFERENCES public.organization(id) NOT NULL,
  bj_member_2_id bigint REFERENCES public.organization(id) NOT NULL,
  winner_id bigint REFERENCES public.organization(id),
  match_type text CHECK (match_type IN ('1vs1', 'rival', 'team_vs_team')) NOT NULL,
  match_order int DEFAULT 1,
  prize_type text,
  prize_amount int,
  match_result jsonb,
  created_at timestamptz DEFAULT now() NOT NULL
);

-- 36. Starcraft Tiers (스타크래프트 티어)
CREATE TABLE IF NOT EXISTS public.starcraft_tiers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  display_order int NOT NULL,
  color text,
  description text,
  created_at timestamptz DEFAULT now() NOT NULL
);

-- 37. Starcraft Tier Members
CREATE TABLE IF NOT EXISTS public.starcraft_tier_members (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tier_id bigint REFERENCES public.starcraft_tiers(id) ON DELETE CASCADE NOT NULL,
  player_name text NOT NULL,
  race text CHECK (race IN ('terran', 'zerg', 'protoss')),
  image_url text,
  description text,
  position_order int DEFAULT 0,
  added_by uuid REFERENCES public.profiles(id),
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);

-- 38. Schedule Event Types
CREATE TABLE IF NOT EXISTS public.schedule_event_types (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text NOT NULL UNIQUE,
  label text NOT NULL,
  color text,
  icon text,
  display_order int DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamptz DEFAULT now() NOT NULL
);

-- =============================================================
-- PART 3: 트리거 & 함수
-- =============================================================

-- 회원가입 시 profiles 자동 생성
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, nickname, email, role)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'nickname', split_part(NEW.email, '@', 1)),
    NEW.email,
    'member'
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- updated_at 자동 업데이트
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS trigger AS $$
BEGIN
  new.updated_at = now();
  return new;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS handle_updated_at ON public.profiles;
CREATE TRIGGER handle_updated_at BEFORE UPDATE ON public.profiles
  FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

DROP TRIGGER IF EXISTS handle_updated_at ON public.notices;
CREATE TRIGGER handle_updated_at BEFORE UPDATE ON public.notices
  FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

DROP TRIGGER IF EXISTS handle_updated_at ON public.posts;
CREATE TRIGGER handle_updated_at BEFORE UPDATE ON public.posts
  FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

DROP TRIGGER IF EXISTS handle_updated_at ON public.banners;
CREATE TRIGGER handle_updated_at BEFORE UPDATE ON public.banners
  FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

DROP TRIGGER IF EXISTS handle_updated_at ON public.tribute_guestbook;
CREATE TRIGGER handle_updated_at BEFORE UPDATE ON public.tribute_guestbook
  FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

DROP TRIGGER IF EXISTS handle_updated_at ON public.prize_penalties;
CREATE TRIGGER handle_updated_at BEFORE UPDATE ON public.prize_penalties
  FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

DROP TRIGGER IF EXISTS handle_updated_at ON public.vip_message_comments;
CREATE TRIGGER handle_updated_at BEFORE UPDATE ON public.vip_message_comments
  FOR EACH ROW EXECUTE PROCEDURE public.handle_updated_at();

-- =============================================================
-- PART 4: 헬퍼 함수
-- =============================================================

CREATE OR REPLACE FUNCTION public.is_admin(user_id uuid)
RETURNS boolean LANGUAGE sql STABLE AS $$
  SELECT EXISTS(
    SELECT 1 FROM public.profiles
    WHERE id = user_id AND role IN ('admin', 'superadmin')
  );
$$;

CREATE OR REPLACE FUNCTION public.is_staff(user_id uuid)
RETURNS boolean LANGUAGE sql STABLE AS $$
  SELECT EXISTS(
    SELECT 1 FROM public.profiles
    WHERE id = user_id AND role IN ('moderator', 'admin', 'superadmin')
  );
$$;

CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean AS $$
BEGIN
  RETURN public.is_admin(auth.uid());
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.is_moderator()
RETURNS boolean AS $$
BEGIN
  RETURN public.is_staff(auth.uid());
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.get_active_season_id()
RETURNS bigint LANGUAGE sql STABLE AS $$
  SELECT id FROM public.seasons
  WHERE is_active = true
  ORDER BY start_date DESC NULLS LAST LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION public.is_vip_user(user_id uuid)
RETURNS boolean LANGUAGE plpgsql STABLE SECURITY DEFINER
SET search_path = public AS $$
DECLARE v_rank integer;
BEGIN
  IF user_id IS NULL THEN RETURN FALSE; END IF;
  IF EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = user_id AND role IN ('vip', 'moderator', 'admin', 'superadmin')
  ) THEN RETURN TRUE; END IF;
  SELECT rank INTO v_rank FROM public.get_user_rank(user_id, NULL) LIMIT 1;
  RETURN v_rank IS NOT NULL AND v_rank <= 50;
END;
$$;

CREATE OR REPLACE FUNCTION public.is_bj_member(user_id uuid)
RETURNS boolean LANGUAGE sql STABLE AS $$
  SELECT EXISTS(
    SELECT 1 FROM public.organization o
    JOIN public.profiles p ON p.id = user_id
    WHERE o.profile_id = user_id AND o.is_active = true
  );
$$;

CREATE OR REPLACE FUNCTION public.get_bj_member_id(user_id uuid)
RETURNS bigint LANGUAGE sql STABLE AS $$
  SELECT o.id FROM public.organization o
  WHERE o.profile_id = user_id AND o.is_active = true
  LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION public.get_user_rank(
  p_user_id uuid,
  p_season_id bigint DEFAULT NULL
)
RETURNS TABLE(rank integer, total_amount bigint)
LANGUAGE plpgsql STABLE SECURITY DEFINER
SET search_path = public AS $$
BEGIN
  IF p_user_id IS NULL THEN RETURN; END IF;
  IF p_season_id IS NULL THEN
    RETURN QUERY
      WITH totals AS (
        SELECT donor_id, sum(amount)::bigint AS total_amount,
               dense_rank() OVER (ORDER BY sum(amount) DESC) AS rank
        FROM public.donations WHERE donor_id IS NOT NULL GROUP BY donor_id
      )
      SELECT totals.rank::integer, totals.total_amount
      FROM totals WHERE totals.donor_id = p_user_id;
  ELSE
    RETURN QUERY
      WITH totals AS (
        SELECT donor_id, sum(amount)::bigint AS total_amount,
               dense_rank() OVER (ORDER BY sum(amount) DESC) AS rank
        FROM public.donations
        WHERE donor_id IS NOT NULL AND season_id = p_season_id
        GROUP BY donor_id
      )
      SELECT totals.rank::integer, totals.total_amount
      FROM totals WHERE totals.donor_id = p_user_id;
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.get_user_rank_active_season(p_user_id uuid)
RETURNS TABLE(rank integer, total_amount bigint, season_id bigint)
LANGUAGE plpgsql STABLE SECURITY DEFINER
SET search_path = public AS $$
DECLARE v_season_id bigint;
BEGIN
  v_season_id := public.get_active_season_id();
  IF v_season_id IS NULL THEN RETURN; END IF;
  RETURN QUERY
    WITH totals AS (
      SELECT d.donor_id, sum(d.amount)::bigint AS total_amount,
             dense_rank() OVER (ORDER BY sum(d.amount) DESC) AS rank
      FROM public.donations d
      WHERE d.donor_id IS NOT NULL AND d.season_id = v_season_id
      GROUP BY d.donor_id
    )
    SELECT totals.rank::integer, totals.total_amount, v_season_id
    FROM totals WHERE totals.donor_id = p_user_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.get_episode_rankings(
  p_episode_id bigint,
  p_limit int DEFAULT 50
)
RETURNS TABLE(rank integer, donor_id uuid, donor_name text, total_amount bigint)
LANGUAGE plpgsql STABLE SECURITY DEFINER
SET search_path = public AS $$
BEGIN
  RETURN QUERY
    WITH totals AS (
      SELECT d.donor_id, d.donor_name, sum(d.amount)::bigint AS total_amount,
             dense_rank() OVER (ORDER BY sum(d.amount) DESC) AS rank
      FROM public.donations d
      WHERE d.episode_id = p_episode_id
      GROUP BY d.donor_id, d.donor_name
    )
    SELECT totals.rank::integer, totals.donor_id, totals.donor_name, totals.total_amount
    FROM totals
    ORDER BY totals.rank
    LIMIT p_limit;
END;
$$;

-- 후원금 총액 자동 업데이트
CREATE OR REPLACE FUNCTION public.update_donation_total()
RETURNS trigger AS $$
BEGIN
  IF (TG_OP = 'INSERT') THEN
    IF (NEW.donor_id IS NOT NULL) THEN
      UPDATE public.profiles SET total_donation = total_donation + NEW.amount WHERE id = NEW.donor_id;
    END IF;
  ELSIF (TG_OP = 'DELETE') THEN
    IF (OLD.donor_id IS NOT NULL) THEN
      UPDATE public.profiles SET total_donation = total_donation - OLD.amount WHERE id = OLD.donor_id;
    END IF;
  ELSIF (TG_OP = 'UPDATE') THEN
    IF (OLD.donor_id IS NOT NULL) THEN
      UPDATE public.profiles SET total_donation = total_donation - OLD.amount WHERE id = OLD.donor_id;
    END IF;
    IF (NEW.donor_id IS NOT NULL) THEN
      UPDATE public.profiles SET total_donation = total_donation + NEW.amount WHERE id = NEW.donor_id;
    END IF;
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_donation_change ON public.donations;
CREATE TRIGGER on_donation_change
  AFTER INSERT OR UPDATE OR DELETE ON public.donations
  FOR EACH ROW EXECUTE PROCEDURE public.update_donation_total();

-- 댓글 수 증감 함수
CREATE OR REPLACE FUNCTION public.increment_comment_count(p_post_id bigint)
RETURNS void LANGUAGE sql AS $$
  UPDATE public.posts SET comment_count = comment_count + 1 WHERE id = p_post_id;
$$;

CREATE OR REPLACE FUNCTION public.decrement_comment_count(p_post_id bigint)
RETURNS void LANGUAGE sql AS $$
  UPDATE public.posts SET comment_count = GREATEST(comment_count - 1, 0) WHERE id = p_post_id;
$$;

-- GRANT
GRANT EXECUTE ON FUNCTION public.get_user_rank(uuid, bigint) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.get_user_rank_active_season(uuid) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.get_episode_rankings(bigint, int) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.is_vip_user(uuid) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.is_admin(uuid) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.is_bj_member(uuid) TO anon, authenticated;

-- =============================================================
-- PART 5: 보안 View (랭킹 데이터)
-- =============================================================

CREATE OR REPLACE VIEW public.total_rankings_public AS
SELECT
  id, rank, donor_name,
  (total_amount * 50) AS viewer_score,
  donation_count, top_bj,
  updated_at, created_at
FROM public.total_donation_rankings;

CREATE OR REPLACE VIEW public.season_rankings_public AS
SELECT
  id, season_id, rank, donor_name,
  (total_amount * 50) AS viewer_score,
  donation_count, unit,
  updated_at, created_at
FROM public.season_donation_rankings;

-- =============================================================
-- PART 6: RLS 정책
-- =============================================================

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.seasons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bj_ranks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.organization ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.episodes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.donations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vip_rewards ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vip_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.signatures ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.signature_videos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.timeline_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notice_attachments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.post_likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.media_content ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.live_status ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.banners ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tribute_guestbook ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bj_thank_you_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vip_personal_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vip_message_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rank_battle_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.total_donation_rankings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.season_donation_rankings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bj_episode_performances ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.legacy_donation_totals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bj_rank_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contribution_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.prize_penalties ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.episode_teams ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.episode_team_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.episode_matchups ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.starcraft_tiers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.starcraft_tier_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.schedule_event_types ENABLE ROW LEVEL SECURITY;

-- === 공개 읽기 테이블 ===
CREATE POLICY "select_public" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "select_public" ON public.seasons FOR SELECT USING (true);
CREATE POLICY "select_public" ON public.bj_ranks FOR SELECT USING (true);
CREATE POLICY "select_public" ON public.organization FOR SELECT USING (true);
CREATE POLICY "select_public" ON public.episodes FOR SELECT USING (true);
CREATE POLICY "select_public" ON public.donations FOR SELECT USING (true);
CREATE POLICY "select_public" ON public.vip_images FOR SELECT USING (true);
CREATE POLICY "select_public" ON public.signatures FOR SELECT USING (true);
CREATE POLICY "select_public" ON public.signature_videos FOR SELECT USING (true);
CREATE POLICY "select_public" ON public.schedules FOR SELECT USING (true);
CREATE POLICY "select_public" ON public.timeline_events FOR SELECT USING (true);
CREATE POLICY "select_public" ON public.notices FOR SELECT USING (true);
CREATE POLICY "select_public" ON public.notice_attachments FOR SELECT USING (true);
CREATE POLICY "select_public" ON public.media_content FOR SELECT USING (true);
CREATE POLICY "select_public" ON public.live_status FOR SELECT USING (true);
CREATE POLICY "select_public" ON public.banners FOR SELECT USING (is_active = true);
CREATE POLICY "select_public" ON public.rank_battle_records FOR SELECT USING (true);
CREATE POLICY "select_public" ON public.bj_episode_performances FOR SELECT USING (true);
CREATE POLICY "select_public" ON public.bj_rank_history FOR SELECT USING (true);
CREATE POLICY "select_public" ON public.episode_teams FOR SELECT USING (true);
CREATE POLICY "select_public" ON public.episode_team_members FOR SELECT USING (true);
CREATE POLICY "select_public" ON public.episode_matchups FOR SELECT USING (true);
CREATE POLICY "select_public" ON public.starcraft_tiers FOR SELECT USING (true);
CREATE POLICY "select_public" ON public.starcraft_tier_members FOR SELECT USING (true);
CREATE POLICY "select_public" ON public.schedule_event_types FOR SELECT USING (true);

-- === 랭킹 테이블: 관리자만 직접 조회 (공개는 View로) ===
CREATE POLICY "select_admin" ON public.total_donation_rankings FOR SELECT USING (public.is_admin(auth.uid()));
CREATE POLICY "select_admin" ON public.season_donation_rankings FOR SELECT USING (public.is_admin(auth.uid()));

-- === 조건부 공개 테이블 ===
CREATE POLICY "select_public" ON public.tribute_guestbook FOR SELECT
  USING (is_approved = true AND is_deleted = false);
CREATE POLICY "select_public" ON public.posts FOR SELECT
  USING (is_deleted = false);
CREATE POLICY "select_public" ON public.comments FOR SELECT
  USING (is_deleted = false);
CREATE POLICY "select_public" ON public.post_likes FOR SELECT USING (true);
CREATE POLICY "select_public" ON public.bj_thank_you_messages FOR SELECT
  USING (is_public = true AND is_deleted = false);
CREATE POLICY "select_public" ON public.vip_personal_messages FOR SELECT
  USING (is_public = true AND is_deleted = false);
CREATE POLICY "select_public" ON public.vip_message_comments FOR SELECT
  USING (is_deleted = false);
CREATE POLICY "select_public" ON public.legacy_donation_totals FOR SELECT USING (true);

-- === 관리자만 기여도/상벌금 직접 조회 ===
CREATE POLICY "select_admin" ON public.contribution_logs FOR SELECT
  USING (public.is_admin(auth.uid()));
CREATE POLICY "select_admin" ON public.prize_penalties FOR SELECT
  USING (public.is_admin(auth.uid()));

-- === 프로필 수정: 본인 또는 스탭 ===
CREATE POLICY "update_own" ON public.profiles FOR UPDATE
  USING (auth.uid() = id OR public.is_staff(auth.uid()));

-- === 인증 사용자 INSERT ===
CREATE POLICY "insert_auth" ON public.posts FOR INSERT
  WITH CHECK (auth.uid() = author_id);
CREATE POLICY "insert_auth" ON public.comments FOR INSERT
  WITH CHECK (auth.uid() = author_id);
CREATE POLICY "insert_auth" ON public.post_likes FOR INSERT
  WITH CHECK (auth.uid() = user_id);
CREATE POLICY "insert_auth" ON public.tribute_guestbook FOR INSERT
  WITH CHECK (auth.uid() = author_id);
CREATE POLICY "insert_auth" ON public.vip_message_comments FOR INSERT
  WITH CHECK (auth.uid() = author_id);

-- === 본인 또는 스탭 UPDATE/DELETE ===
CREATE POLICY "update_own_or_staff" ON public.posts FOR UPDATE
  USING (auth.uid() = author_id OR public.is_staff(auth.uid()));
CREATE POLICY "delete_own_or_staff" ON public.posts FOR DELETE
  USING (auth.uid() = author_id OR public.is_staff(auth.uid()));
CREATE POLICY "update_own_or_staff" ON public.comments FOR UPDATE
  USING (auth.uid() = author_id OR public.is_staff(auth.uid()));
CREATE POLICY "delete_own_or_staff" ON public.comments FOR DELETE
  USING (auth.uid() = author_id OR public.is_staff(auth.uid()));
CREATE POLICY "delete_own" ON public.post_likes FOR DELETE
  USING (auth.uid() = user_id);

-- === VIP 전용 ===
CREATE POLICY "select_vip" ON public.vip_rewards FOR SELECT
  USING (profile_id = auth.uid() OR public.is_staff(auth.uid()));

-- === 스탭 전체 권한 ===
CREATE POLICY "all_staff" ON public.seasons FOR ALL
  USING (public.is_staff(auth.uid()));
CREATE POLICY "all_staff" ON public.organization FOR ALL
  USING (public.is_staff(auth.uid()));
CREATE POLICY "all_staff" ON public.episodes FOR ALL
  USING (public.is_staff(auth.uid()));
CREATE POLICY "all_staff" ON public.donations FOR ALL
  USING (public.is_staff(auth.uid()));
CREATE POLICY "all_staff" ON public.vip_rewards FOR ALL
  USING (public.is_staff(auth.uid()));
CREATE POLICY "all_staff" ON public.vip_images FOR ALL
  USING (public.is_staff(auth.uid()));
CREATE POLICY "all_staff" ON public.signatures FOR ALL
  USING (public.is_staff(auth.uid()));
CREATE POLICY "all_staff" ON public.signature_videos FOR ALL
  USING (public.is_staff(auth.uid()));
CREATE POLICY "all_staff" ON public.schedules FOR ALL
  USING (public.is_staff(auth.uid()));
CREATE POLICY "all_staff" ON public.timeline_events FOR ALL
  USING (public.is_staff(auth.uid()));
CREATE POLICY "all_staff" ON public.notices FOR ALL
  USING (public.is_staff(auth.uid()));
CREATE POLICY "all_staff" ON public.notice_attachments FOR ALL
  USING (public.is_staff(auth.uid()));
CREATE POLICY "all_staff" ON public.media_content FOR ALL
  USING (public.is_staff(auth.uid()));
CREATE POLICY "all_staff" ON public.live_status FOR ALL
  USING (public.is_staff(auth.uid()));
CREATE POLICY "all_staff" ON public.banners FOR ALL
  USING (public.is_staff(auth.uid()));
CREATE POLICY "all_staff" ON public.schedule_event_types FOR ALL
  USING (public.is_staff(auth.uid()));

-- === 관리자 전체 권한 ===
CREATE POLICY "all_admin" ON public.profiles FOR ALL
  USING (public.is_admin(auth.uid()));
CREATE POLICY "all_admin" ON public.bj_ranks FOR ALL
  USING (public.is_admin(auth.uid()));
CREATE POLICY "all_admin" ON public.rank_battle_records FOR ALL
  USING (public.is_admin(auth.uid()));
CREATE POLICY "all_admin" ON public.total_donation_rankings FOR ALL
  USING (public.is_admin(auth.uid()));
CREATE POLICY "all_admin" ON public.season_donation_rankings FOR ALL
  USING (public.is_admin(auth.uid()));
CREATE POLICY "all_admin" ON public.bj_episode_performances FOR ALL
  USING (public.is_admin(auth.uid()));
CREATE POLICY "all_admin" ON public.legacy_donation_totals FOR ALL
  USING (public.is_admin(auth.uid()));
CREATE POLICY "all_admin" ON public.bj_rank_history FOR ALL
  USING (public.is_admin(auth.uid()));
CREATE POLICY "all_admin" ON public.contribution_logs FOR ALL
  USING (public.is_admin(auth.uid()));
CREATE POLICY "all_admin" ON public.prize_penalties FOR ALL
  USING (public.is_admin(auth.uid()));
CREATE POLICY "all_admin" ON public.episode_teams FOR ALL
  USING (public.is_admin(auth.uid()));
CREATE POLICY "all_admin" ON public.episode_team_members FOR ALL
  USING (public.is_admin(auth.uid()));
CREATE POLICY "all_admin" ON public.episode_matchups FOR ALL
  USING (public.is_admin(auth.uid()));
CREATE POLICY "all_admin" ON public.starcraft_tiers FOR ALL
  USING (public.is_admin(auth.uid()));
CREATE POLICY "all_admin" ON public.starcraft_tier_members FOR ALL
  USING (public.is_admin(auth.uid()));
CREATE POLICY "all_admin" ON public.bj_thank_you_messages FOR ALL
  USING (public.is_admin(auth.uid()));
CREATE POLICY "all_admin" ON public.vip_personal_messages FOR ALL
  USING (public.is_admin(auth.uid()));
CREATE POLICY "all_admin" ON public.vip_message_comments FOR ALL
  USING (public.is_admin(auth.uid()));
CREATE POLICY "all_admin" ON public.tribute_guestbook FOR ALL
  USING (public.is_admin(auth.uid()));

-- =============================================================
-- PART 7: 인덱스
-- =============================================================

CREATE INDEX IF NOT EXISTS idx_donations_season ON public.donations(season_id);
CREATE INDEX IF NOT EXISTS idx_donations_donor ON public.donations(donor_id);
CREATE INDEX IF NOT EXISTS idx_donations_episode ON public.donations(episode_id);
CREATE INDEX IF NOT EXISTS idx_donations_amount ON public.donations(amount DESC);
CREATE INDEX IF NOT EXISTS idx_posts_board ON public.posts(board_type);
CREATE INDEX IF NOT EXISTS idx_posts_created ON public.posts(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_comments_post ON public.comments(post_id);
CREATE INDEX IF NOT EXISTS idx_org_unit ON public.organization(unit);
CREATE INDEX IF NOT EXISTS idx_org_parent ON public.organization(parent_id);
CREATE INDEX IF NOT EXISTS idx_notices_pinned ON public.notices(is_pinned DESC, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_timeline_season ON public.timeline_events(season_id, order_index);
CREATE INDEX IF NOT EXISTS idx_schedules_datetime ON public.schedules(start_datetime);
CREATE INDEX IF NOT EXISTS idx_profiles_role ON public.profiles(role);
CREATE INDEX IF NOT EXISTS idx_profiles_donation ON public.profiles(total_donation DESC);
CREATE INDEX IF NOT EXISTS idx_guestbook_tribute ON public.tribute_guestbook(tribute_user_id);
CREATE INDEX IF NOT EXISTS idx_guestbook_created ON public.tribute_guestbook(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_banners_active ON public.banners(is_active, display_order) WHERE is_active = true;
CREATE INDEX IF NOT EXISTS idx_signatures_unit ON public.signatures(unit);
CREATE INDEX IF NOT EXISTS idx_sig_videos_sig ON public.signature_videos(signature_id);
CREATE INDEX IF NOT EXISTS idx_sig_videos_member ON public.signature_videos(member_id);
CREATE INDEX IF NOT EXISTS idx_live_member ON public.live_status(member_id);
CREATE INDEX IF NOT EXISTS idx_live_live ON public.live_status(is_live) WHERE is_live = true;
CREATE INDEX IF NOT EXISTS idx_vip_rewards_season ON public.vip_rewards(season_id);
CREATE INDEX IF NOT EXISTS idx_media_type ON public.media_content(content_type);
CREATE INDEX IF NOT EXISTS idx_episodes_season ON public.episodes(season_id);
CREATE INDEX IF NOT EXISTS idx_rank_battle_season ON public.rank_battle_records(season_id, battle_number);
CREATE INDEX IF NOT EXISTS idx_bj_perf_episode ON public.bj_episode_performances(episode_id);
CREATE INDEX IF NOT EXISTS idx_bj_rank_history_member ON public.bj_rank_history(bj_member_id);
CREATE INDEX IF NOT EXISTS idx_contribution_member ON public.contribution_logs(bj_member_id);
CREATE INDEX IF NOT EXISTS idx_prize_member ON public.prize_penalties(bj_member_id);
CREATE INDEX IF NOT EXISTS idx_sc_tier_members ON public.starcraft_tier_members(tier_id);

-- =============================================================
-- 완료! 38개 테이블 + View + RLS + 함수 + 인덱스
-- =============================================================
